# Podfile used by cocoapods-rome

platform :osx, '10.12'

# remove everithing in { } after new release of cocoapods-rome

plugin 'cocoapods-rome', { :pre_compile => Proc.new { |installer| 
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '5.0'
        end
    end

    installer.pods_project.save
},

    dsym: false,
    configuration: 'Release'
}

target 'caesar' do
pod 'Yaml', '3.4.4'
end
